name: flamingo
#-$(echo `date '+%Y%m%d%H%M%S'`)
on:
  push:
    branches:
      - 'master'
    paths:
      - 'trigger/flamingo'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Master Build
    env:
      PROJ_VER: foo
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Evaluate dependency cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JAR
        id: mvn-pkg
        run: |
          mvn -B clean package
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout > target/ver
          echo "::set-env name=PROJ_VER::$(cat target/ver)"
#      - name: Enable SSH debugging
#        uses: mxschmitt/action-tmate@v1
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: playground-vx${{ env.PROJ_VER }}.jar
          path: target/playground.jar
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Package
    needs: build
    steps:
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: playground-v${{ env.PROJ_VER }}.jar
      - name: Build Docker Image
        id: dockerize
        run: |
          mkdir -p target
          cp artifact/playground*.jar target/playground.jar
          docker build -t docker.pkg.github.com/mrazjava/playground/flamingo .
      - name: Push image to Github Packages
        run: |
          docker login -u mrazjava -p ${{ secrets.GITHUB_PACKAGES }} docker.pkg.github.com
          docker push docker.pkg.github.com/mrazjava/playground/flamingo