name: flamingo
#-$(echo `date '+%Y%m%d%H%M%S'`)
on:
  push:
    branches:
      - 'master'
    paths:
      - 'trigger/flamingo'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Evaluate dependency cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JAR
        id: mvn-pkg
        run: |
          mvn -B clean package
      - name: Extract Project Version
        id: mvn-help-eval
        run: |
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout > target/project.version
          echo "::set-output name=project-version::$(cat target/project.version)"
#      - name: Enable SSH debugging
#        uses: mxschmitt/action-tmate@v1
      - name: Upload project.version artifact
        uses: actions/upload-artifact@v1
        with:
          name: flamingo
          path: target/project.version, target/playground.jar, Dockerfile
  deploy:
    runs-on: ubuntu-latest
    name: Package and Deploy
    needs: build
    steps:
      - name: Download project.version artifact
        uses: actions/download-artifact@v1
        with:
          name: flamingo
      - name: Fetch project version
        id: fetch-proj-ver
        run: |
          echo "::set-output name=project-version::$(cat flamingo/project.version)"
      - name: Build Docker Image
        id: dockerize
        run: |
          mkdir -p target/
          mv flamingo/playground.jar target/
          docker build -t docker.pkg.github.com/mrazjava/playground/flamingo .
      - name: Push image to Github Packages
        run: |
          docker login -u mrazjava -p ${{ secrets.GITHUB_PACKAGES }} docker.pkg.github.com
          docker push docker.pkg.github.com/mrazjava/playground/flamingo