name: master
#-$(echo `date '+%Y%m%d%H%M%S'`)
on:
  push:
    branches:
      - master/garbage/mvnver
jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Master Build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Evaluate dependency cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JAR
        id: mvn-pkg
        run: |
          mvn -B clean package
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout > target/ver
          echo "::set-output name=project-version::$(cat target/ver)"
#      - name: Enable SSH debugging
#        uses: mxschmitt/action-tmate@v1
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: playground-v${{ steps.mvn-pkg.outputs.project-version }}.jar
          path: target/playground.jar

